/* VERBMASTER · ANÁLISIS MORFOLÓGICO POR NIVELES */

const ANA_LEVELS = [
  {id:1,name:'Presente en indicativo',short:'Presente',desc:'Formas simples en presente de indicativo con verbos frecuentes. El objetivo es automatizar infinitivo, persona y número.',modos:['indicativo'],tiempos:['indPres'],verbos:['cantar','bailar','hablar','estudiar','trabajar','comer','beber','vivir','partir','subir'],target:5},
  {id:2,name:'Pasados básicos',short:'Pasados',desc:'Pretérito imperfecto y pretérito perfecto simple de indicativo. Atención a las terminaciones del pasado.',modos:['indicativo'],tiempos:['indImp','indPS'],verbos:['cantar','hablar','estudiar','comer','beber','vivir','partir','ser','estar','ir'],target:5},
  {id:3,name:'Irregulares frecuentes',short:'Irregulares',desc:'Indicativo simple con verbos irregulares de uso común: ser, estar, ir, tener, hacer, decir, poder…',modos:['indicativo'],tiempos:['indPres','indImp','indPS'],verbos:['ser','estar','ir','tener','hacer','decir','poder','poner','venir','dar','saber','querer','ver'],target:6},
  {id:4,name:'Futuro y condicional',short:'Futuro',desc:'Futuro simple y condicional simple. Empieza a diferenciar tiempos que se parecen en su estructura.',modos:['indicativo'],tiempos:['indFut','indCond'],verbos:null,target:6},
  {id:5,name:'Presente de subjuntivo',short:'Subj. pres.',desc:'Entrada al subjuntivo: presente simple. La ruleta de modo ya marca subjuntivo; aquí te centras en el tiempo.',modos:['subjuntivo'],tiempos:['subjPres'],verbos:null,target:6},
  {id:6,name:'Imperfecto de subjuntivo',short:'Subj. imp.',desc:'Pretérito imperfecto de subjuntivo en sus dos variantes: -ra y -se.',modos:['subjuntivo'],tiempos:['subjImp','subjImpEse'],verbos:null,target:6},
  {id:7,name:'Compuestas de indicativo',short:'Comp. ind.',desc:'Formas compuestas de indicativo: haber conjugado + participio.',modos:['indicativo'],tiempos:['indPerfComp','indPluscuamp','indFutComp','indCondComp'],verbos:null,target:6},
  {id:8,name:'Compuestas de subjuntivo',short:'Comp. subj.',desc:'Formas compuestas del subjuntivo. Exige reconocer modo, tiempo, auxiliar y participio.',modos:['subjuntivo'],tiempos:['subjPerfComp','subjPluscuamp','subjPluscuampEse'],verbos:null,target:6},
  {id:9,name:'Mezcla total',short:'Maestría',desc:'Todos los modos y tiempos de la app mezclados. Es el nivel de dominio global.',modos:['indicativo','subjuntivo'],tiempos:null,verbos:null,target:8}
];

Object.assign(ST,{modoAna:'int',nivelActual:1,nivelMax:1,nivelOk:0,nivelErr:0,ejercicios:0,scoreOk:0,scoreErr:0,anaActual:null});

function nivel(){return ANA_LEVELS.find(n=>n.id===ST.nivelActual)||ANA_LEVELS[0];}
function tiempoById(id){for(const modo of Object.keys(TIEMPOS)){const all=[...TIEMPOS[modo].simples,...TIEMPOS[modo].compuestos];const found=all.find(t=>t.id===id);if(found)return{modo,tiempoObj:found};}return null;}
function tiemposParaNivel(lv){if(lv.tiempos)return lv.tiempos.map(tiempoById).filter(Boolean);const lista=[];lv.modos.forEach(modo=>{[...TIEMPOS[modo].simples,...TIEMPOS[modo].compuestos].forEach(tiempoObj=>lista.push({modo,tiempoObj}));});return lista;}
function verbosParaNivel(lv){return lv.verbos&&lv.verbos.length?lv.verbos.filter(v=>VERBOS[v]):Object.keys(VERBOS);}

function setNivel(id,force=false){if(!force&&id>ST.nivelMax)return;ST.nivelActual=Math.max(1,Math.min(id,ANA_LEVELS.length));ST.nivelOk=0;ST.nivelErr=0;renderRuta();nuevaFormaAna();}
function nuevaFormaAna(){const lv=nivel();const tiempos=tiemposParaNivel(lv);const item=rand(tiempos);const claves=verbosParaNivel(lv);const verboKey=rand(claves);const verboDato=VERBOS[verboKey];const personaObj=rand(PERSONAS);const forma=getForma(verboKey,item.tiempoObj,personaObj.idx);const esSimple=!item.tiempoObj.haberKey;ST.anaActual={personaObj,modo:item.modo,tiempoObj:item.tiempoObj,verboKey,verboDato,forma,esSimple};el('anaForma').textContent=forma;el('feedbackInt').classList.add('hidden');el('solucionInt').classList.add('hidden');buildInteractivo();renderRuta();}

function camposActivos(){return{inf:el('chkInf').checked,per:el('chkPer').checked,num:el('chkNum').checked,mod:el('chkMod').checked,tie:el('chkTie').checked,tip:el('chkTip').checked};}
function buildInteractivo(){const grid=el('interactivoGrid');grid.innerHTML='';const show=camposActivos();const optsPersona=PERSONAS.map(p=>p.persona).filter((v,i,a)=>a.indexOf(v)===i);const optsNumero=['singular','plural'];const optsModo=['indicativo','subjuntivo'];const optsTiempos=[...new Set([...TIEMPOS.indicativo.simples,...TIEMPOS.indicativo.compuestos,...TIEMPOS.subjuntivo.simples,...TIEMPOS.subjuntivo.compuestos].map(t=>t.label))];const optsTipo=['simple','compuesta'];if(show.inf)grid.innerHTML+=iField('iInf','📝 Infinitivo',Object.keys(VERBOS));if(show.per)grid.innerHTML+=iField('iPer','👤 Persona',optsPersona);if(show.num)grid.innerHTML+=iField('iNum','🔢 Número',optsNumero);if(show.mod)grid.innerHTML+=iField('iMod','📚 Modo',optsModo);if(show.tie)grid.innerHTML+=iField('iTie','⏱️ Tiempo',optsTiempos);if(show.tip)grid.innerHTML+=iField('iTip','📋 Tipo',optsTipo);}
function iField(id,lbl,opciones){const opts=opciones.map(o=>`<option value="${o}">${o}</option>`).join('');return `<div class="ifield"><label for="${id}">${lbl}</label><select class="iselect" id="${id}"><option value="">– elige –</option>${opts}</select></div>`;}

function corregirInteractivo(){const r=ST.anaActual;if(!r){nuevaFormaAna();return;}const show=camposActivos();let correctas=0,total=0;const esSingular=r.personaObj.numero==='singular';const esPrimOTerc=r.personaObj.idx===0||r.personaObj.idx===2;const ambigua=esSingular&&esPrimOTerc&&formaAmbigua13(r.verboKey,r.tiempoObj);function chk(chkKey,selectId,valorCorrecto){if(!show[chkKey])return;const sel=el(selectId);if(!sel)return;total++;const resp=sel.value.trim().toLowerCase();const ok=resp===valorCorrecto.toLowerCase();sel.className='iselect '+(ok?'sel-ok':'sel-err');if(ok)correctas++;}if(show.per){const sel=el('iPer');if(sel){total++;const resp=sel.value.trim().toLowerCase();const correcto=r.personaObj.persona.toLowerCase();let ok=resp===correcto;if(!ok&&ambigua&&(resp==='1.ª persona'||resp==='3.ª persona'))ok=true;sel.className='iselect '+(ok?'sel-ok':'sel-err');if(ok)correctas++;}}chk('inf','iInf',r.verboKey);chk('num','iNum',r.personaObj.numero);chk('mod','iMod',r.modo);chk('tie','iTie',r.tiempoObj.label);chk('tip','iTip',r.esSimple?'simple':'compuesta');if(total===0){alert('Activa al menos un aspecto a analizar.');return;}ST.ejercicios++;const perfecto=correctas===total;if(perfecto){ST.scoreOk++;ST.nivelOk++;}else{ST.scoreErr++;ST.nivelErr++;}renderFeedback(correctas,total,ambigua,perfecto);renderSolucion(r,show,ambigua);if(perfecto&&ST.nivelOk>=nivel().target)completarNivel();else renderRuta();}
function renderFeedback(correctas,total,ambigua,perfecto){const fb=el('feedbackInt');fb.classList.remove('hidden','fb-ok','fb-par','fb-err');let fbClass,fbText;if(perfecto){fbClass='fb-ok';fbText='✅ Perfecto. Sumas un avance en esta misión.';if(ambigua)fbText+=' Nota: esta forma admite 1.ª o 3.ª persona del singular.';}else if(correctas>0){fbClass='fb-par';fbText=`⚠️ ${correctas} de ${total} correctas. Mira las marcadas en rojo y compara con la solución.`;}else{fbClass='fb-err';fbText='❌ Ninguna correcta. Observa la solución y prueba otra forma.';}fb.className='feedback '+fbClass;fb.textContent=fbText;}
function renderSolucion(r,show,ambigua){const sol=el('solucionInt');sol.classList.remove('hidden');let sHTML='<div class="reveal-grid">';if(show.inf)sHTML+=revItem('📝 Infinitivo',r.verboKey);if(show.per){const notaPersona=ambigua?r.personaObj.persona+' <small style="opacity:.75">(o '+(r.personaObj.idx===0?'3.ª':'1.ª')+' persona: forma idéntica)</small>':r.personaObj.persona;sHTML+=revItem('👤 Persona',notaPersona);}if(show.num)sHTML+=revItem('🔢 Número',r.personaObj.numero);if(show.mod)sHTML+=revItem('📚 Modo',r.modo);if(show.tie)sHTML+=revItem('⏱️ Tiempo',r.tiempoObj.label);if(show.tip)sHTML+=revItem('📋 Tipo',r.esSimple?'simple':'compuesta');sHTML+='</div><div class="flex-c mt-14"><button class="btn btn-primary btn-sm" onclick="nuevaFormaAna()">➡️ Siguiente forma</button></div>';sol.innerHTML=sHTML;}
function revItem(lbl,val){return `<div class="rev-item"><div class="rev-lbl">${lbl}</div><div class="rev-val">${val}</div></div>`;}
function completarNivel(){const actual=nivel();if(ST.nivelMax<actual.id+1&&actual.id<ANA_LEVELS.length)ST.nivelMax=actual.id+1;const fb=el('feedbackInt');fb.className='feedback fb-ok';fb.textContent=actual.id<ANA_LEVELS.length?`🏆 Misión completada: ${actual.name}. Nivel ${actual.id+1} desbloqueado.`:'🏆 Ruta completada. Ya estás en el nivel de mezcla total.';renderRuta();}
function renderRuta(){const lv=nivel();el('counterPill').textContent='Nivel '+ST.nivelActual;el('missionTitle').textContent=`Nivel ${lv.id}: ${lv.name}`;el('missionDesc').textContent=lv.desc;el('progressText').textContent=`${Math.min(ST.nivelOk,lv.target)} / ${lv.target} aciertos perfectos`;el('sessionText').textContent=`Sesión: ${ST.scoreOk} aciertos · ${ST.scoreErr} errores`;el('progressFill').style.width=Math.min(100,(ST.nivelOk/lv.target)*100)+'%';const strip=el('levelStrip');strip.innerHTML=ANA_LEVELS.map(n=>{const locked=n.id>ST.nivelMax;const active=n.id===ST.nivelActual;return `<button class="level-pill ${active?'active':''} ${locked?'locked':''}" onclick="setNivel(${n.id})" title="${n.name}">${locked?'🔒':'✓'} ${n.id}. ${n.short}</button>`;}).join('');const teacher=el('teacherLevels');if(teacher)teacher.innerHTML=ANA_LEVELS.map(n=>`<button class="btn btn-secondary btn-xs" onclick="setNivel(${n.id}, true); if(ST.nivelMax < ${n.id}) ST.nivelMax=${n.id}; renderRuta();">Nivel ${n.id}</button>`).join('');}
function codigoActual(){const base=`ANA-N${ST.nivelMax}-A${ST.scoreOk}-E${ST.scoreErr}-R${ST.ejercicios}`;const checksum=base.split('').reduce((acc,ch)=>acc+ch.charCodeAt(0),0)%97;return `${base}-C${String(checksum).padStart(2,'0')}`;}
function finalizarSesion(){const panel=el('sessionSummary');const lv=nivel();const code=codigoActual();panel.classList.remove('hidden');panel.innerHTML=`<div class="summary-card"><div class="card-title">🏁 Sesión finalizada</div><h2>Copia este código en la libreta</h2><div class="summary-grid"><div><strong>Nivel desbloqueado</strong><span>${ST.nivelMax}</span></div><div><strong>Nivel actual</strong><span>${lv.id}: ${lv.short}</span></div><div><strong>Aciertos</strong><span>${ST.scoreOk}</span></div><div><strong>Errores</strong><span>${ST.scoreErr}</span></div></div><div class="code-box" id="finalCode">${code}</div><div class="flex-c mt-14"><button class="btn btn-primary" onclick="copiarCodigo()">📋 Copiar código</button><button class="btn btn-secondary" onclick="window.print()">🖨️ Imprimir</button></div><p class="text-muted" style="text-align:center;margin-top:12px">El código no contiene nombre ni datos personales. Solo resume el progreso de esta sesión.</p></div>`;panel.scrollIntoView({behavior:'smooth',block:'start'});}
function copiarCodigo(){const txt=el('finalCode')?.textContent||codigoActual();navigator.clipboard?.writeText(txt);}
function abrirCodigo(){const panel=el('codePanel');panel.classList.remove('hidden');panel.innerHTML=`<div class="summary-card"><div class="card-title">🔑 Continuar con código</div><h2>Introduce el código de la libreta</h2><p class="text-muted">Formato esperado: ANA-N4-A18-E3-R21-C00. Solo usaremos el nivel desbloqueado y el marcador.</p><div class="code-input-row"><input id="resumeCode" class="code-input" placeholder="ANA-N4-A18-E3-R21-C00"><button class="btn btn-primary" onclick="usarCodigo()">Continuar</button></div><div id="codeMsg" class="hidden"></div></div>`;panel.scrollIntoView({behavior:'smooth',block:'start'});}
function usarCodigo(){const raw=(el('resumeCode').value||'').trim().toUpperCase();const msg=el('codeMsg');const m=raw.match(/^ANA-N(\d+)-A(\d+)-E(\d+)-R(\d+)-C(\d{2})$/);if(!m){msg.className='feedback fb-err';msg.textContent='Código no reconocido. Revisa guiones, letras y números.';return;}const n=Math.max(1,Math.min(parseInt(m[1],10),ANA_LEVELS.length));ST.nivelMax=n;ST.scoreOk=parseInt(m[2],10)||0;ST.scoreErr=parseInt(m[3],10)||0;ST.ejercicios=parseInt(m[4],10)||0;ST.nivelOk=0;ST.nivelErr=0;setNivel(n,true);msg.className='feedback fb-ok';msg.textContent=`Código cargado. Continúas desde el nivel ${n}.`;}
function reiniciarRuta(){ST.nivelActual=1;ST.nivelMax=1;ST.nivelOk=0;ST.nivelErr=0;ST.scoreOk=0;ST.scoreErr=0;ST.ejercicios=0;el('sessionSummary').classList.add('hidden');el('codePanel').classList.add('hidden');renderRuta();nuevaFormaAna();}
function desbloquearTodo(){ST.nivelMax=ANA_LEVELS.length;renderRuta();}
function escucharAna(){if(ST.anaActual)hablar(ST.anaActual.forma);}
window.addEventListener('DOMContentLoaded',()=>{['chkInf','chkPer','chkNum','chkMod','chkTie','chkTip'].forEach(id=>{const c=el(id);if(c)c.addEventListener('change',buildInteractivo);});renderRuta();nuevaFormaAna();});
