const BLOCKS = [
  {
    id: "b1",
    title: "Errores evidentes",
    description: "Casos sencillos para entrar en modo detective.",
    levels: [
      { title: "Tabla sospechosa", text: "7 × 8 = 54", instruction: "Localiza el error de cálculo.", type: "calculo", answerIndex: 1, options: ["El 7", "El resultado 54", "El signo ×", "No hay error"], hint: "Recuerda la tabla del 8.", explanation: "7 × 8 no es 54, sino 56. El error está en el resultado." },
      { title: "Frase torcida", text: "Los niño juegan en el patio.", instruction: "Encuentra el problema de concordancia.", type: "lengua", answerIndex: 0, options: ["Los niño", "juegan", "en el patio", "No hay error"], hint: "Mira si artículo y nombre coinciden en número.", explanation: "Debe decir «Los niños juegan...» porque el artículo está en plural." },
      { title: "Animal imposible", text: "El pez salió volando del acuario y se posó en un árbol.", instruction: "Detecta el dato imposible.", type: "ciencias", answerIndex: 1, options: ["El pez", "salió volando", "del acuario", "un árbol"], hint: "Piensa qué puede hacer normalmente un pez.", explanation: "Un pez no puede salir volando y posarse en un árbol. Es un dato imposible en una situación normal." },
      { title: "Suma distraída", text: "125 + 40 = 145", instruction: "Comprueba la operación.", type: "calculo", answerIndex: 2, options: ["125", "+", "145", "No hay error"], hint: "Suma primero 100 + 40.", explanation: "125 + 40 = 165. El resultado 145 es incorrecto." },
      { title: "Día raro", text: "Ayer fue lunes y mañana también será lunes.", instruction: "Busca la contradicción temporal.", type: "logica", answerIndex: 1, options: ["Ayer fue lunes", "mañana también será lunes", "La palabra ayer", "No hay error"], hint: "Entre ayer y mañana pasan dos días.", explanation: "Si ayer fue lunes, hoy es martes y mañana será miércoles. No puede ser lunes otra vez." },
      { title: "Orden imposible", text: "Para lavarte las manos: primero sécalas, después mójalas y al final ponte jabón.", instruction: "Detecta el problema en las instrucciones.", type: "instrucciones", answerIndex: 0, options: ["primero sécalas", "después mójalas", "ponte jabón", "No hay error"], hint: "Piensa qué paso debe ir al final.", explanation: "No tiene sentido secarse las manos antes de mojarlas y enjabonarlas. El orden está mal." },
      { title: "Capital confundida", text: "La capital de Francia es Roma.", instruction: "Localiza el dato incorrecto.", type: "ciencias", answerIndex: 2, options: ["capital", "Francia", "Roma", "No hay error"], hint: "Roma es capital de otro país.", explanation: "La capital de Francia es París. Roma es la capital de Italia." },
      { title: "Reto final del bloque", text: "Si tengo 10 caramelos y regalo 3, ahora tengo 13.", instruction: "Encuentra el error y explica la operación correcta.", type: "calculo", answerIndex: 2, options: ["tengo 10", "regalo 3", "ahora tengo 13", "No hay error"], hint: "Regalar reduce la cantidad.", explanation: "Si regalo 3 caramelos, no sumo: resto. 10 − 3 = 7." }
    ]
  },
  {
    id: "b2",
    title: "Errores matemáticos",
    description: "Decimales, unidades, problemas y operaciones con trampa.",
    levels: [
      { title: "Kilómetros encogidos", text: "3,5 km = 350 m", instruction: "Revisa la conversión de unidades.", type: "unidades", answerIndex: 1, options: ["3,5 km", "350 m", "El signo =", "No hay error"], hint: "1 km son 1000 m.", explanation: "3,5 km equivalen a 3500 m, no a 350 m." },
      { title: "Perímetro disfrazado", text: "Un cuadrado de lado 5 cm tiene un área de 20 cm².", instruction: "Distingue área y perímetro.", type: "calculo", answerIndex: 2, options: ["cuadrado", "lado 5 cm", "área de 20 cm²", "No hay error"], hint: "El área del cuadrado es lado × lado.", explanation: "20 cm sería el perímetro. El área es 5 × 5 = 25 cm²." },
      { title: "Coma viajera", text: "456 cm = 45,6 m", instruction: "Comprueba el cambio de centímetros a metros.", type: "unidades", answerIndex: 1, options: ["456 cm", "45,6 m", "El signo =", "No hay error"], hint: "100 cm son 1 m.", explanation: "456 cm son 4,56 m. Se ha movido mal la coma." },
      { title: "Precio imposible", text: "Compro 3 libretas de 2 € cada una. Pago 5 € en total.", instruction: "Comprueba si el total corresponde al precio unitario.", type: "calculo", answerIndex: 2, options: ["3 libretas", "2 € cada una", "Pago 5 €", "No hay error"], hint: "Multiplica cantidad por precio.", explanation: "3 libretas de 2 € cuestan 6 €. El total de 5 € es incorrecto." },
      { title: "Dato innecesario", text: "Lucía tiene 12 años, compra 4 lápices a 1 € cada uno y paga 4 €.", instruction: "¿Hay error o solo un dato que no hace falta?", type: "sin_error", answerIndex: 3, options: ["12 años", "4 lápices", "1 € cada uno", "No hay error"], hint: "Que un dato no haga falta no significa que sea falso.", explanation: "No hay error matemático. La edad es un dato innecesario, pero no contradice el problema." },
      { title: "Mitad mal pensada", text: "La mitad de 90 es 40.", instruction: "Comprueba la mitad.", type: "calculo", answerIndex: 1, options: ["La mitad", "40", "90", "No hay error"], hint: "Busca dos números iguales que sumen 90.", explanation: "La mitad de 90 es 45, porque 45 + 45 = 90." },
      { title: "Resultado correcto, explicación mala", text: "25 × 4 = 100 porque 25 + 4 = 100.", instruction: "El resultado es correcto, pero revisa el razonamiento.", type: "logica", answerIndex: 2, options: ["25 × 4", "100", "porque 25 + 4 = 100", "No hay error"], hint: "Una respuesta puede estar bien por una razón equivocada.", explanation: "25 × 4 sí es 100, pero 25 + 4 no es 100. La explicación es falsa." },
      { title: "Reto final matemático", text: "Un rectángulo mide 8 cm de largo y 3 cm de ancho. Su perímetro es 24 cm².", instruction: "Hay un error sutil: localízalo.", type: "unidades", answerIndex: 2, options: ["8 cm de largo", "3 cm de ancho", "24 cm²", "No hay error"], hint: "El perímetro no se mide en unidades cuadradas.", explanation: "El perímetro sería 22 cm, y además se mide en cm, no en cm²." }
    ]
  },
  {
    id: "b3",
    title: "Errores de lengua",
    description: "Concordancia, puntuación, tiempos verbales y sentido de las frases.",
    levels: [
      { title: "Plural escondido", text: "La pandilla de niñas llegaron tarde.", instruction: "Revisa la concordancia entre sujeto y verbo.", type: "lengua", answerIndex: 2, options: ["La pandilla", "de niñas", "llegaron", "No hay error"], hint: "El núcleo del sujeto no siempre es la palabra más cercana al verbo.", explanation: "El núcleo es «pandilla», singular. Lo adecuado es «La pandilla de niñas llegó tarde»." },
      { title: "Coma peligrosa", text: "Vamos a comer niños.", instruction: "Encuentra el problema de puntuación.", type: "lengua", answerIndex: 2, options: ["Vamos", "a comer", "niños", "No hay error"], hint: "Una coma puede cambiar completamente el sentido.", explanation: "Falta la coma del vocativo: «Vamos a comer, niños». Sin coma parece que se va a comer a los niños." },
      { title: "Tiempo verbal roto", text: "Mañana fui al museo con mi clase.", instruction: "Detecta el problema temporal.", type: "lengua", answerIndex: 1, options: ["Mañana", "fui", "al museo", "No hay error"], hint: "Mañana habla de futuro; mira el verbo.", explanation: "«Mañana» exige futuro: «Mañana iré al museo». «Fui» es pasado." },
      { title: "Pronombre confundido", text: "A Marta la dije que viniera pronto.", instruction: "Localiza el error de uso del pronombre.", type: "lengua", answerIndex: 1, options: ["A Marta", "la dije", "que viniera", "No hay error"], hint: "Pregunta: ¿a quién dije algo?", explanation: "Lo normativo es «A Marta le dije...» porque Marta es complemento indirecto." },
      { title: "Mayúscula fugada", text: "visitamos gijón durante el puente.", instruction: "Revisa mayúsculas necesarias.", type: "lengua", answerIndex: 1, options: ["visitamos", "gijón", "durante", "No hay error"], hint: "Los nombres propios se escriben con mayúscula inicial.", explanation: "Debe escribirse «Gijón», con mayúscula inicial por ser nombre propio." },
      { title: "Ambigüedad sospechosa", text: "Vi a Pablo con los prismáticos.", instruction: "Indica si hay un error claro o una ambigüedad.", type: "informacion", answerIndex: 3, options: ["Vi", "Pablo", "los prismáticos", "Información insuficiente"], hint: "Puede significar dos cosas distintas.", explanation: "No sabemos si yo usé prismáticos para ver a Pablo o si Pablo llevaba los prismáticos. Falta información." },
      { title: "Concordancia de género", text: "La agua fría está en la mesa.", instruction: "Revisa si realmente hay error.", type: "lengua", answerIndex: 0, options: ["La", "agua", "fría", "No hay error"], hint: "Cuidado: «agua» usa artículo especial en singular.", explanation: "Sí habría que decir «el agua fría», así que hay error en el artículo. Este caso exige fijarse bien." },
      { title: "Reto final de lengua", text: "Si habría estudiado más, aprobaría.", instruction: "Detecta el error verbal.", type: "lengua", answerIndex: 0, options: ["Si habría estudiado", "más", "aprobaría", "No hay error"], hint: "Después de «si» condicional no va «habría» en esa estructura.", explanation: "Lo correcto es «Si hubiera/hubiese estudiado más, aprobaría»." }
    ]
  },
  {
    id: "b4",
    title: "Errores de lógica",
    description: "Conclusiones falsas, contradicciones y razonamientos incompletos.",
    levels: [
      { title: "Todos no significa algunos", text: "Todos los perros son animales. Mi gato es animal. Entonces mi gato es perro.", instruction: "Detecta la conclusión falsa.", type: "logica", answerIndex: 2, options: ["Todos los perros son animales", "Mi gato es animal", "Entonces mi gato es perro", "No hay error"], hint: "Que A esté dentro de B no significa que todo B sea A.", explanation: "La conclusión no se deduce. Hay muchos animales que no son perros." },
      { title: "Causa dudosa", text: "Me puse la camiseta roja y ganamos el partido. Ganamos por mi camiseta.", instruction: "Busca la falsa relación de causa.", type: "logica", answerIndex: 2, options: ["camiseta roja", "ganamos", "por mi camiseta", "No hay error"], hint: "Que dos hechos ocurran juntos no prueba causa.", explanation: "No hay pruebas de que la camiseta causara la victoria." },
      { title: "Contradicción directa", text: "La caja está completamente vacía y dentro hay tres canicas.", instruction: "Localiza la contradicción.", type: "logica", answerIndex: 0, options: ["completamente vacía", "dentro", "tres canicas", "No hay error"], hint: "Vacía significa que no contiene nada.", explanation: "Si hay tres canicas dentro, la caja no está completamente vacía." },
      { title: "Conclusión precipitada", text: "Dos alumnos llegaron tarde hoy. La clase entera es impuntual.", instruction: "Detecta la generalización incorrecta.", type: "logica", answerIndex: 2, options: ["Dos alumnos", "hoy", "La clase entera", "No hay error"], hint: "Una muestra pequeña no representa necesariamente al grupo entero.", explanation: "No se puede concluir que toda la clase sea impuntual por dos alumnos un día." },
      { title: "Orden imposible", text: "Nací en 2015 y en 2010 ya jugaba en el patio del colegio.", instruction: "Busca la incoherencia temporal.", type: "logica", answerIndex: 1, options: ["Nací en 2015", "en 2010 ya jugaba", "patio del colegio", "No hay error"], hint: "2010 ocurrió antes de 2015.", explanation: "No se puede jugar en 2010 si se nació en 2015." },
      { title: "Doble condición", text: "Para entrar necesitas carné y entrada. Tengo entrada, así que puedo entrar.", instruction: "Revisa si se cumplen todas las condiciones.", type: "logica", answerIndex: 2, options: ["necesitas carné y entrada", "Tengo entrada", "puedo entrar", "No hay error"], hint: "La palabra «y» exige dos requisitos.", explanation: "Falta saber si tiene carné. Con solo la entrada no basta." },
      { title: "No hay error", text: "Si llueve, el suelo se moja. Está lloviendo, así que el suelo se moja.", instruction: "Comprueba si el razonamiento es válido.", type: "sin_error", answerIndex: 3, options: ["Si llueve", "Está lloviendo", "el suelo se moja", "No hay error"], hint: "Aquí se cumple la condición inicial.", explanation: "No hay error lógico: si la condición se cumple, la consecuencia tiene sentido." },
      { title: "Reto final lógico", text: "Nadie de mi equipo sabe nadar. Ana es de mi equipo y nada muy bien.", instruction: "Localiza la contradicción.", type: "logica", answerIndex: 0, options: ["Nadie de mi equipo sabe nadar", "Ana es de mi equipo", "nada muy bien", "No hay error"], hint: "Si nadie sabe, Ana tampoco debería saber.", explanation: "Las dos afirmaciones se contradicen: Ana pertenece al equipo y sí sabe nadar." }
    ]
  },
  {
    id: "b5",
    title: "Instrucciones y algoritmos",
    description: "Pasos desordenados, condiciones incorrectas y órdenes ambiguas.",
    levels: [
      { title: "Receta al revés", text: "Para hacer una tostada: unta la mantequilla, mete el pan en la tostadora y espera.", instruction: "Detecta el paso desordenado.", type: "instrucciones", answerIndex: 0, options: ["unta la mantequilla", "mete el pan", "espera", "No hay error"], hint: "Primero hay que tostar el pan.", explanation: "La mantequilla debe untarse después de tostar el pan." },
      { title: "Robot despistado", text: "Avanza 3 pasos, gira a la derecha, avanza 2 pasos. Objetivo: llegar a una casilla situada 3 pasos al frente.", instruction: "Busca la instrucción innecesaria o equivocada.", type: "instrucciones", answerIndex: 1, options: ["Avanza 3 pasos", "gira a la derecha", "avanza 2 pasos", "No hay error"], hint: "El objetivo está justo delante.", explanation: "Si el objetivo está 3 pasos al frente, girar a la derecha y avanzar más aleja al robot." },
      { title: "Bucle infinito", text: "Mientras la puerta esté cerrada, espera. La puerta está cerrada con llave y nadie tiene la llave.", instruction: "Detecta por qué el plan falla.", type: "instrucciones", answerIndex: 0, options: ["Mientras la puerta esté cerrada, espera", "con llave", "nadie tiene la llave", "No hay error"], hint: "Una espera sin cambio posible no termina.", explanation: "El algoritmo puede quedarse esperando para siempre porque nada hará que la puerta se abra." },
      { title: "Condición incompleta", text: "Si tienes más de 10 puntos, ganas. Tienes exactamente 10 puntos.", instruction: "¿Puede decirse que gana?", type: "informacion", answerIndex: 3, options: ["más de 10", "ganas", "exactamente 10", "Información insuficiente"], hint: "Más de 10 no incluye 10.", explanation: "No gana con esa regla, pero falta saber qué ocurre con exactamente 10 puntos." },
      { title: "Orden de búsqueda", text: "Busca la palabra en el diccionario empezando por la última letra.", instruction: "Localiza el problema del procedimiento.", type: "instrucciones", answerIndex: 1, options: ["Busca", "empezando por la última letra", "diccionario", "No hay error"], hint: "Los diccionarios se ordenan desde la primera letra.", explanation: "Para buscar una palabra se empieza por la primera letra, no por la última." },
      { title: "Instrucción ambigua", text: "Coloca el libro cerca de la ventana.", instruction: "Detecta el problema de precisión.", type: "informacion", answerIndex: 1, options: ["Coloca", "cerca", "ventana", "No hay error"], hint: "Cerca puede significar distancias distintas.", explanation: "La orden es ambigua: no dice exactamente dónde ni a qué distancia." },
      { title: "No hay error algorítmico", text: "Para comprobar una suma: calcula, repite la operación y compara los dos resultados.", instruction: "Valora si el procedimiento es correcto.", type: "sin_error", answerIndex: 3, options: ["calcula", "repite", "compara", "No hay error"], hint: "Es una estrategia razonable de revisión.", explanation: "No hay error. Repetir y comparar ayuda a detectar fallos." },
      { title: "Reto final de algoritmos", text: "Si la respuesta es correcta, vuelve a intentarlo. Si es incorrecta, pasa al siguiente nivel.", instruction: "Encuentra la condición invertida.", type: "instrucciones", answerIndex: 0, options: ["Si la respuesta es correcta", "vuelve a intentarlo", "Si es incorrecta", "pasa al siguiente nivel"], hint: "Normalmente se avanza al acertar.", explanation: "Las acciones están invertidas: al acertar debería avanzar, y al fallar debería intentarlo otra vez." }
    ]
  },
  {
    id: "b6",
    title: "Ciencias y sociedad",
    description: "Afirmaciones falsas, causalidades dudosas y conocimiento general.",
    levels: [
      { title: "Planeta equivocado", text: "El Sol gira alrededor de la Tierra una vez al día.", instruction: "Detecta el error científico.", type: "ciencias", answerIndex: 0, options: ["El Sol gira alrededor de la Tierra", "una vez", "al día", "No hay error"], hint: "Piensa en el movimiento de rotación de la Tierra.", explanation: "La apariencia diaria se debe sobre todo a la rotación terrestre, no a que el Sol gire alrededor de la Tierra." },
      { title: "Hielo pesado", text: "El hielo se hunde siempre en el agua porque pesa más.", instruction: "Localiza la afirmación falsa.", type: "ciencias", answerIndex: 0, options: ["El hielo se hunde siempre", "en el agua", "porque pesa más", "No hay error"], hint: "Piensa en un vaso con cubitos.", explanation: "El hielo normalmente flota en el agua líquida porque es menos denso." },
      { title: "Voto animal", text: "Los delfines eligen alcalde cada cuatro años.", instruction: "Detecta el dato imposible o absurdo.", type: "ciencias", answerIndex: 1, options: ["Los delfines", "eligen alcalde", "cada cuatro años", "No hay error"], hint: "Una elección política es una organización humana.", explanation: "Los delfines no celebran elecciones municipales ni eligen alcaldes." },
      { title: "Causa meteorológica", text: "Hoy hace frío porque mi vecino abrió la ventana.", instruction: "Busca la falsa causa.", type: "logica", answerIndex: 2, options: ["Hoy hace frío", "mi vecino", "porque abrió la ventana", "No hay error"], hint: "Una ventana puede enfriar una habitación, no el tiempo de todo el día.", explanation: "Abrir una ventana no causa el tiempo atmosférico general." },
      { title: "Reciclaje confuso", text: "El papel usado se tira siempre al contenedor amarillo.", instruction: "Localiza el error de conocimiento social.", type: "ciencias", answerIndex: 2, options: ["El papel usado", "se tira", "contenedor amarillo", "No hay error"], hint: "El amarillo suele ser para envases.", explanation: "El papel y cartón van al contenedor azul, no al amarillo." },
      { title: "Medicamento mágico", text: "Si un jarabe curó a una persona, cura siempre a todo el mundo.", instruction: "Detecta la generalización peligrosa.", type: "logica", answerIndex: 2, options: ["un jarabe", "curó a una persona", "cura siempre a todo el mundo", "No hay error"], hint: "Un caso no demuestra una regla universal.", explanation: "No se puede concluir que funcione siempre y para todos por un solo caso." },
      { title: "No hay error social", text: "Para cruzar con seguridad conviene mirar a ambos lados antes de pasar.", instruction: "Comprueba si hay error.", type: "sin_error", answerIndex: 3, options: ["cruzar", "mirar", "ambos lados", "No hay error"], hint: "Es una norma básica de seguridad vial.", explanation: "No hay error: mirar a ambos lados reduce el riesgo al cruzar." },
      { title: "Reto final ciencia", text: "Las plantas no respiran: solo respiran los animales.", instruction: "Detecta el error científico.", type: "ciencias", answerIndex: 0, options: ["Las plantas no respiran", "solo", "los animales", "No hay error"], hint: "Las plantas también intercambian gases.", explanation: "Las plantas también respiran, aunque además realizan fotosíntesis." }
    ]
  },
  {
    id: "b7",
    title: "Errores escondidos",
    description: "Casos donde el fallo no está donde parece.",
    levels: [
      { title: "Respuesta correcta, unidad falsa", text: "5 m + 30 cm = 530 cm²", instruction: "No mires solo el número: revisa la unidad.", type: "unidades", answerIndex: 2, options: ["5 m", "30 cm", "530 cm²", "No hay error"], hint: "Las longitudes no se expresan en cm².", explanation: "El número 530 puede ser correcto en centímetros, pero la unidad debe ser cm, no cm²." },
      { title: "La trampa del cero", text: "0 × 835 = 835", instruction: "Comprueba la multiplicación.", type: "calculo", answerIndex: 2, options: ["0", "835", "= 835", "No hay error"], hint: "Multiplicar por cero siempre da cero.", explanation: "0 × 835 = 0, no 835." },
      { title: "Titular sin dato", text: "La mayoría de la clase prefiere ajedrez. Se preguntó a 3 alumnos de 25.", instruction: "Busca el problema de información.", type: "informacion", answerIndex: 1, options: ["La mayoría", "3 alumnos de 25", "prefiere ajedrez", "No hay error"], hint: "Tres respuestas no bastan para hablar de toda la clase.", explanation: "La muestra es demasiado pequeña para afirmar qué prefiere la mayoría de la clase." },
      { title: "Error en la pregunta", text: "¿Cuánto pesa una distancia de 4 kilómetros?", instruction: "Detecta por qué la pregunta está mal formulada.", type: "unidades", answerIndex: 1, options: ["pesa", "distancia", "4 kilómetros", "No hay error"], hint: "Peso y distancia son magnitudes distintas.", explanation: "Una distancia no pesa. Se están mezclando magnitudes incompatibles." },
      { title: "El dato que sobra", text: "En una caja hay 6 pelotas rojas y 4 azules. ¿Cuántas pelotas hay en total? La caja es verde.", instruction: "Decide si hay error o dato irrelevante.", type: "sin_error", answerIndex: 3, options: ["6 rojas", "4 azules", "La caja es verde", "No hay error"], hint: "Un dato puede sobrar sin ser falso.", explanation: "No hay error. Que la caja sea verde no afecta al total: 6 + 4 = 10." },
      { title: "Comparación injusta", text: "Mi equipo es mejor porque ganó un partido amistoso contra niños dos años menores.", instruction: "Localiza el punto débil del razonamiento.", type: "logica", answerIndex: 2, options: ["ganó", "partido amistoso", "niños dos años menores", "No hay error"], hint: "La comparación no está en igualdad de condiciones.", explanation: "Ganar a un grupo mucho menor no demuestra necesariamente que el equipo sea mejor en general." },
      { title: "Instrucción imposible", text: "Escribe una palabra de cinco letras usando solo cuatro letras.", instruction: "Detecta la incompatibilidad.", type: "instrucciones", answerIndex: 1, options: ["palabra", "cinco letras", "solo cuatro letras", "No hay error"], hint: "Cinco y cuatro no pueden cumplirse a la vez en esa orden.", explanation: "La instrucción pide dos condiciones incompatibles: cinco letras y solo cuatro letras." },
      { title: "Reto final escondido", text: "El tren salió a las 10:00 y llegó a las 9:45 del mismo día. El viaje duró 15 minutos.", instruction: "Busca el error temporal escondido.", type: "logica", answerIndex: 1, options: ["salió a las 10:00", "llegó a las 9:45", "mismo día", "15 minutos"], hint: "En el mismo día no puedes llegar antes de salir.", explanation: "Si es el mismo día, llegar a las 9:45 antes de salir a las 10:00 es imposible." }
    ]
  },
  {
    id: "b8",
    title: "Casi fake news",
    description: "Titulares engañosos, exageraciones y conclusiones sin pruebas.",
    levels: [
      { title: "Titular exagerado", text: "Un niño comió espinacas y sacó un 10. Las espinacas garantizan aprobar.", instruction: "Detecta la conclusión sin pruebas.", type: "logica", answerIndex: 2, options: ["Un niño", "sacó un 10", "garantizan aprobar", "No hay error"], hint: "Un caso aislado no garantiza nada.", explanation: "No se puede afirmar que las espinacas garanticen aprobar por un solo ejemplo." },
      { title: "Porcentaje tramposo", text: "El 100% de los encuestados quiere más recreo. Se encuestó a una persona.", instruction: "Localiza el problema del dato.", type: "informacion", answerIndex: 2, options: ["100%", "más recreo", "una persona", "No hay error"], hint: "El porcentaje parece fuerte, pero la muestra es mínima.", explanation: "El 100% de una sola persona no permite representar la opinión del grupo." },
      { title: "Fuente misteriosa", text: "Dicen que beber agua azul mejora la memoria, pero nadie sabe quién lo investigó.", instruction: "Detecta la falta de fuente fiable.", type: "informacion", answerIndex: 2, options: ["Dicen que", "agua azul", "nadie sabe quién lo investigó", "No hay error"], hint: "Una afirmación necesita fuente comprobable.", explanation: "La afirmación no aporta fuente ni evidencia. «Dicen que» no basta." },
      { title: "Foto engañosa", text: "La foto muestra una calle inundada. Titular: Toda Asturias está bajo el agua.", instruction: "Busca la exageración.", type: "logica", answerIndex: 2, options: ["una calle", "inundada", "Toda Asturias", "No hay error"], hint: "Una calle no representa toda una comunidad.", explanation: "Se exagera desde un caso local a una afirmación total." },
      { title: "Antes no significa por eso", text: "El colegio cambió el menú y al día siguiente llovió. El menú causó la lluvia.", instruction: "Detecta falsa causalidad.", type: "logica", answerIndex: 2, options: ["cambió el menú", "llovió", "causó la lluvia", "No hay error"], hint: "Que algo ocurra antes no lo convierte en causa.", explanation: "No hay relación probada entre el menú del colegio y la lluvia." },
      { title: "Número sin contexto", text: "Han aumentado los robos en 2 casos. Titular: Aumento brutal de robos.", instruction: "Localiza el problema del titular.", type: "informacion", answerIndex: 2, options: ["aumentado", "2 casos", "Aumento brutal", "No hay error"], hint: "Falta saber el total y comparar con otros periodos.", explanation: "Decir «brutal» con solo 2 casos puede ser engañoso si no hay contexto." },
      { title: "Publicidad disfrazada", text: "El mejor lápiz del mundo, según la empresa que lo vende.", instruction: "Detecta el posible conflicto de interés.", type: "informacion", answerIndex: 2, options: ["mejor lápiz", "del mundo", "empresa que lo vende", "No hay error"], hint: "La fuente se beneficia de que creas el mensaje.", explanation: "La empresa que vende el producto no es una fuente neutral para afirmar que es el mejor." },
      { title: "Reto final fake news", text: "Tres personas dicen que vieron un dragón. Por tanto, los dragones existen seguro.", instruction: "Detecta la conclusión no demostrada.", type: "logica", answerIndex: 2, options: ["Tres personas", "vieron un dragón", "existen seguro", "No hay error"], hint: "Testimonios no verificados no son prueba suficiente.", explanation: "La conclusión es demasiado fuerte: harían falta pruebas verificables, no solo testimonios." }
    ]
  }
];
